# Generated by Django 3.0.2 on 2020-01-19 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendStatus', models.CharField(choices=[('p', 'Present'), ('a', 'Absent')], default='a', help_text='Attendance Status', max_length=1)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GeoPolygon',
            fields=[
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('office_branch', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
