# Generated by Django 3.0.2 on 2020-01-19 12:17

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendreport',
            name='office_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.GeoPolygon'),
        ),
        migrations.CreateModel(
            name='eDetail',
            fields=[
                ('eID', models.IntegerField(default=1, help_text='Employee ID', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('office_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.GeoPolygon')),
            ],
        ),
        migrations.AddField(
            model_name='attendreport',
            name='eID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.eDetail'),
        ),
        
    ]
