# Generated by Django 3.0.2 on 2020-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edetail',
            name='office_branch',
            field=models.CharField(max_length=20),
        ),
    ]
