# Generated by Django 3.0.2 on 2020-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200120_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendreport',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
