# Generated by Django 3.0.2 on 2020-01-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('office_branch', models.CharField(help_text='Enter the Branch of the office at the location given by latitude and longitude', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('office_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.GeoLocation')),
            ],
        ),
        migrations.CreateModel(
            name='aReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendStatus', models.CharField(choices=[('p', 'Present'), ('a', 'Absent')], default='a', help_text='Attendance Status', max_length=1)),
                ('eID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.eDetails')),
                ('geoLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.GeoLocation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
